site_name: SwiftCLI
site_description: Build testable CLI apps with click and pydantic
repo_url: https://github.com/orlevii/swiftcli
theme:
  name: material
  features:
    - navigation.sections
    - navigation.expand
    - navigation.top
    - content.code.copy
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep purple
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)" 
      scheme: slate
      primary: deep purple
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - admonition
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - tables
  - def_list

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - User Guide:
    - Parameter Types: user-guide/parameter-types.md
    - Command Configuration: user-guide/command-configuration.md
    - Testing: user-guide/testing.md
